/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_task = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_intent = 4,
  anon_sym_input = 5,
  anon_sym_output = 6,
  anon_sym_compute = 7,
  anon_sym_agent = 8,
  anon_sym_constraints = 9,
  anon_sym_verify = 10,
  anon_sym_COLON = 11,
  anon_sym_QMARK = 12,
  aux_sym__raw_block_token1 = 13,
  sym__string = 14,
  sym__triple_string = 15,
  sym_comment = 16,
  aux_sym__field_identifier_token1 = 17,
  sym_source_file = 18,
  sym_task_declaration = 19,
  sym__task_member = 20,
  sym_intent_block = 21,
  sym_input_block = 22,
  sym_output_block = 23,
  sym_compute_block = 24,
  sym_agent_block = 25,
  sym_constraints_block = 26,
  sym_verify_block = 27,
  sym__field_block = 28,
  sym__field_declaration = 29,
  sym__type_reference = 30,
  sym__raw_block = 31,
  sym__field_identifier = 32,
  sym_identifier = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_task_declaration_repeat1 = 35,
  aux_sym__field_block_repeat1 = 36,
  aux_sym__raw_block_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_task] = "task",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_intent] = "intent",
  [anon_sym_input] = "input",
  [anon_sym_output] = "output",
  [anon_sym_compute] = "compute",
  [anon_sym_agent] = "agent",
  [anon_sym_constraints] = "constraints",
  [anon_sym_verify] = "verify",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK] = "\?",
  [aux_sym__raw_block_token1] = "_raw_block_token1",
  [sym__string] = "_string",
  [sym__triple_string] = "_triple_string",
  [sym_comment] = "comment",
  [aux_sym__field_identifier_token1] = "_field_identifier_token1",
  [sym_source_file] = "source_file",
  [sym_task_declaration] = "task_declaration",
  [sym__task_member] = "_task_member",
  [sym_intent_block] = "intent_block",
  [sym_input_block] = "input_block",
  [sym_output_block] = "output_block",
  [sym_compute_block] = "compute_block",
  [sym_agent_block] = "agent_block",
  [sym_constraints_block] = "constraints_block",
  [sym_verify_block] = "verify_block",
  [sym__field_block] = "_field_block",
  [sym__field_declaration] = "_field_declaration",
  [sym__type_reference] = "_type_reference",
  [sym__raw_block] = "_raw_block",
  [sym__field_identifier] = "_field_identifier",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_task_declaration_repeat1] = "task_declaration_repeat1",
  [aux_sym__field_block_repeat1] = "_field_block_repeat1",
  [aux_sym__raw_block_repeat1] = "_raw_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_task] = anon_sym_task,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_intent] = anon_sym_intent,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_compute] = anon_sym_compute,
  [anon_sym_agent] = anon_sym_agent,
  [anon_sym_constraints] = anon_sym_constraints,
  [anon_sym_verify] = anon_sym_verify,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [aux_sym__raw_block_token1] = aux_sym__raw_block_token1,
  [sym__string] = sym__string,
  [sym__triple_string] = sym__triple_string,
  [sym_comment] = sym_comment,
  [aux_sym__field_identifier_token1] = aux_sym__field_identifier_token1,
  [sym_source_file] = sym_source_file,
  [sym_task_declaration] = sym_task_declaration,
  [sym__task_member] = sym__task_member,
  [sym_intent_block] = sym_intent_block,
  [sym_input_block] = sym_input_block,
  [sym_output_block] = sym_output_block,
  [sym_compute_block] = sym_compute_block,
  [sym_agent_block] = sym_agent_block,
  [sym_constraints_block] = sym_constraints_block,
  [sym_verify_block] = sym_verify_block,
  [sym__field_block] = sym__field_block,
  [sym__field_declaration] = sym__field_declaration,
  [sym__type_reference] = sym__type_reference,
  [sym__raw_block] = sym__raw_block,
  [sym__field_identifier] = sym__field_identifier,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_task_declaration_repeat1] = aux_sym_task_declaration_repeat1,
  [aux_sym__field_block_repeat1] = aux_sym__field_block_repeat1,
  [aux_sym__raw_block_repeat1] = aux_sym__raw_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_task] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_intent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_compute] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_agent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_constraints] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_verify] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__raw_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym__triple_string] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__field_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_task_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__task_member] = {
    .visible = false,
    .named = true,
  },
  [sym_intent_block] = {
    .visible = true,
    .named = true,
  },
  [sym_input_block] = {
    .visible = true,
    .named = true,
  },
  [sym_output_block] = {
    .visible = true,
    .named = true,
  },
  [sym_compute_block] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_block] = {
    .visible = true,
    .named = true,
  },
  [sym_constraints_block] = {
    .visible = true,
    .named = true,
  },
  [sym_verify_block] = {
    .visible = true,
    .named = true,
  },
  [sym__field_block] = {
    .visible = false,
    .named = true,
  },
  [sym__field_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__type_reference] = {
    .visible = false,
    .named = true,
  },
  [sym__raw_block] = {
    .visible = false,
    .named = true,
  },
  [sym__field_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_task_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__field_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__raw_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_type = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_type, 1, .inherited = true},
  [2] =
    {field_type, 0, .inherited = true},
  [3] =
    {field_type, 0, .inherited = true},
    {field_type, 1, .inherited = true},
  [5] =
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(48);
      ADVANCE_MAP(
        '"', 2,
        '/', 8,
        ':', 59,
        '?', 60,
        'a', 16,
        'c', 25,
        'i', 21,
        'o', 42,
        't', 9,
        'v', 11,
        '{', 50,
        '}', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(63);
      if (lookahead == '}') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(64);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(65);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(67);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '?') ADVANCE(60);
      if (lookahead == '}') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(68);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(46);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'k') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(27);
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(43);
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(45);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 46:
      if (lookahead == 'y') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_task);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_intent);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_compute);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_agent);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_constraints);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_verify);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__raw_block_token1);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(68);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__raw_block_token1);
      if (lookahead == '/') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym__raw_block_token1);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym__raw_block_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__string);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__string);
      if (lookahead == '"') ADVANCE(7);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__triple_string);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__field_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_task] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_intent] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_compute] = ACTIONS(1),
    [anon_sym_agent] = ACTIONS(1),
    [anon_sym_constraints] = ACTIONS(1),
    [anon_sym_verify] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [sym__string] = ACTIONS(1),
    [sym__triple_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(41),
    [sym_task_declaration] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_task] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_intent,
    ACTIONS(13), 1,
      anon_sym_input,
    ACTIONS(15), 1,
      anon_sym_output,
    ACTIONS(17), 1,
      anon_sym_compute,
    ACTIONS(19), 1,
      anon_sym_agent,
    ACTIONS(21), 1,
      anon_sym_constraints,
    ACTIONS(23), 1,
      anon_sym_verify,
    STATE(3), 9,
      sym__task_member,
      sym_intent_block,
      sym_input_block,
      sym_output_block,
      sym_compute_block,
      sym_agent_block,
      sym_constraints_block,
      sym_verify_block,
      aux_sym_task_declaration_repeat1,
  [39] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_intent,
    ACTIONS(13), 1,
      anon_sym_input,
    ACTIONS(15), 1,
      anon_sym_output,
    ACTIONS(17), 1,
      anon_sym_compute,
    ACTIONS(19), 1,
      anon_sym_agent,
    ACTIONS(21), 1,
      anon_sym_constraints,
    ACTIONS(23), 1,
      anon_sym_verify,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(4), 9,
      sym__task_member,
      sym_intent_block,
      sym_input_block,
      sym_output_block,
      sym_compute_block,
      sym_agent_block,
      sym_constraints_block,
      sym_verify_block,
      aux_sym_task_declaration_repeat1,
  [78] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 1,
      anon_sym_intent,
    ACTIONS(32), 1,
      anon_sym_input,
    ACTIONS(35), 1,
      anon_sym_output,
    ACTIONS(38), 1,
      anon_sym_compute,
    ACTIONS(41), 1,
      anon_sym_agent,
    ACTIONS(44), 1,
      anon_sym_constraints,
    ACTIONS(47), 1,
      anon_sym_verify,
    STATE(4), 9,
      sym__task_member,
      sym_intent_block,
      sym_input_block,
      sym_output_block,
      sym_compute_block,
      sym_agent_block,
      sym_constraints_block,
      sym_verify_block,
      aux_sym_task_declaration_repeat1,
  [117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [145] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 8,
      anon_sym_RBRACE,
      anon_sym_intent,
      anon_sym_input,
      anon_sym_output,
      anon_sym_compute,
      anon_sym_agent,
      anon_sym_constraints,
      anon_sym_verify,
  [271] = 4,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(76), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym__raw_block_repeat1,
    ACTIONS(74), 3,
      aux_sym__raw_block_token1,
      sym__string,
      sym__triple_string,
  [286] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      aux_sym__field_identifier_token1,
    STATE(19), 1,
      aux_sym__field_block_repeat1,
    STATE(35), 1,
      sym__field_declaration,
    STATE(42), 1,
      sym__field_identifier,
  [305] = 4,
    ACTIONS(76), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym__raw_block_repeat1,
    ACTIONS(84), 3,
      aux_sym__raw_block_token1,
      sym__string,
      sym__triple_string,
  [320] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      aux_sym__field_identifier_token1,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym__field_block_repeat1,
    STATE(35), 1,
      sym__field_declaration,
    STATE(42), 1,
      sym__field_identifier,
  [339] = 4,
    ACTIONS(76), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym__raw_block_repeat1,
    ACTIONS(90), 3,
      aux_sym__raw_block_token1,
      sym__string,
      sym__triple_string,
  [354] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      aux_sym__field_identifier_token1,
    STATE(21), 1,
      aux_sym__field_block_repeat1,
    STATE(35), 1,
      sym__field_declaration,
    STATE(42), 1,
      sym__field_identifier,
  [373] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 1,
      anon_sym_task,
    STATE(22), 2,
      sym_task_declaration,
      aux_sym_source_file_repeat1,
  [387] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_task,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    STATE(22), 2,
      sym_task_declaration,
      aux_sym_source_file_repeat1,
  [401] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      aux_sym__field_identifier_token1,
    STATE(25), 1,
      sym__field_identifier,
    STATE(34), 1,
      sym__type_reference,
  [414] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_QMARK,
    ACTIONS(107), 2,
      anon_sym_RBRACE,
      aux_sym__field_identifier_token1,
  [425] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      aux_sym__field_identifier_token1,
    STATE(38), 1,
      sym_identifier,
  [435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_task,
  [443] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym__raw_block,
  [453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym__field_block,
  [463] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(5), 1,
      sym__field_block,
  [473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_task,
  [481] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym__raw_block,
  [491] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym__raw_block,
  [501] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_RBRACE,
      aux_sym__field_identifier_token1,
  [509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_RBRACE,
      aux_sym__field_identifier_token1,
  [517] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym__raw_block,
  [527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      aux_sym__field_identifier_token1,
  [535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
  [542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym__string,
  [549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
  [556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
  [563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 131,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 159,
  [SMALL_STATE(9)] = 173,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 201,
  [SMALL_STATE(12)] = 215,
  [SMALL_STATE(13)] = 229,
  [SMALL_STATE(14)] = 243,
  [SMALL_STATE(15)] = 257,
  [SMALL_STATE(16)] = 271,
  [SMALL_STATE(17)] = 286,
  [SMALL_STATE(18)] = 305,
  [SMALL_STATE(19)] = 320,
  [SMALL_STATE(20)] = 339,
  [SMALL_STATE(21)] = 354,
  [SMALL_STATE(22)] = 373,
  [SMALL_STATE(23)] = 387,
  [SMALL_STATE(24)] = 401,
  [SMALL_STATE(25)] = 414,
  [SMALL_STATE(26)] = 425,
  [SMALL_STATE(27)] = 435,
  [SMALL_STATE(28)] = 443,
  [SMALL_STATE(29)] = 453,
  [SMALL_STATE(30)] = 463,
  [SMALL_STATE(31)] = 473,
  [SMALL_STATE(32)] = 481,
  [SMALL_STATE(33)] = 491,
  [SMALL_STATE(34)] = 501,
  [SMALL_STATE(35)] = 509,
  [SMALL_STATE(36)] = 517,
  [SMALL_STATE(37)] = 527,
  [SMALL_STATE(38)] = 535,
  [SMALL_STATE(39)] = 542,
  [SMALL_STATE(40)] = 549,
  [SMALL_STATE(41)] = 556,
  [SMALL_STATE(42)] = 563,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 2, 0, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__raw_block, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intent_block, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_block, 2, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compute_block, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_block, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraints_block, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verify_block, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__raw_block, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 3, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__raw_block_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__raw_block_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 4),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 4), SHIFT_REPEAT(42),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_reference, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_declaration, 4, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_declaration, 5, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_declaration, 3, 0, 5),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 1, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_reference, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_forma(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
